#!/usr/bin/env bash
set -euo pipefail

required=(
  CLAWSWEEPER_ADAPTER_ARTIFACT_DIR
  CLAWSWEEPER_ADAPTER_SCHEMA_DIR
  CLAWSWEEPER_ADAPTER_TARGET_DIR
  CLAWSWEEPER_COPILOT_EFFORT
  CLAWSWEEPER_COPILOT_HOME
  CLAWSWEEPER_COPILOT_DECISION_MCP
  CLAWSWEEPER_COPILOT_MODEL
  CLAWSWEEPER_MODEL_GIT_CONFIG
  CLAWSWEEPER_MODEL_HOME
  CLAWSWEEPER_MODEL_PATH
  CLAWSWEEPER_MODEL_USER
  CLAWSWEEPER_PROOF_SCRATCH_DIR
  CLAWSWEEPER_REAL_CODEX
  CLAWSWEEPER_REAL_COPILOT
  COPILOT_GITHUB_TOKEN
)
for name in "${required[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    echo "$name is required" >&2
    exit 2
  fi
done

if [[ ! "$CLAWSWEEPER_MODEL_USER" =~ ^[a-z_][a-z0-9_-]*$ ]]; then
  echo "CLAWSWEEPER_MODEL_USER is invalid" >&2
  exit 2
fi
if [[ "$CLAWSWEEPER_REAL_CODEX" != /* || ! -x "$CLAWSWEEPER_REAL_CODEX" ]]; then
  echo "CLAWSWEEPER_REAL_CODEX must be an absolute executable path" >&2
  exit 2
fi
if [[ "$CLAWSWEEPER_MODEL_HOME" != /* || "$CLAWSWEEPER_COPILOT_HOME" != /* ]]; then
  echo "model home paths must be absolute" >&2
  exit 2
fi
if [[ "$CLAWSWEEPER_MODEL_GIT_CONFIG" != /* || ! -r "$CLAWSWEEPER_MODEL_GIT_CONFIG" ]]; then
  echo "CLAWSWEEPER_MODEL_GIT_CONFIG must be an absolute readable path" >&2
  exit 2
fi
if [[ "$CLAWSWEEPER_PROOF_SCRATCH_DIR" != /* ]]; then
  echo "CLAWSWEEPER_PROOF_SCRATCH_DIR must be absolute" >&2
  exit 2
fi
for name in \
  CLAWSWEEPER_ADAPTER_ARTIFACT_DIR \
  CLAWSWEEPER_ADAPTER_SCHEMA_DIR \
  CLAWSWEEPER_ADAPTER_TARGET_DIR \
  CLAWSWEEPER_COPILOT_DECISION_MCP \
  CLAWSWEEPER_REAL_COPILOT; do
  if [[ "${!name}" != /* ]]; then
    echo "$name must be absolute" >&2
    exit 2
  fi
done
if [[ ! -x "$CLAWSWEEPER_REAL_COPILOT" ]]; then
  echo "CLAWSWEEPER_REAL_COPILOT must be executable" >&2
  exit 2
fi
if [[ ! -x "$CLAWSWEEPER_COPILOT_DECISION_MCP" ]]; then
  echo "CLAWSWEEPER_COPILOT_DECISION_MCP must be executable" >&2
  exit 2
fi
if [[ "$CLAWSWEEPER_COPILOT_MODEL" != "gpt-5.6-terra" ]]; then
  echo "CLAWSWEEPER_COPILOT_MODEL is not admitted" >&2
  exit 2
fi
if [[ "$CLAWSWEEPER_COPILOT_EFFORT" != "high" ]]; then
  echo "CLAWSWEEPER_COPILOT_EFFORT is not admitted" >&2
  exit 2
fi

exec /usr/bin/sudo --non-interactive --set-home --user="$CLAWSWEEPER_MODEL_USER" -- \
  /usr/bin/env -i \
    HOME="$CLAWSWEEPER_MODEL_HOME" \
    COPILOT_HOME="$CLAWSWEEPER_COPILOT_HOME" \
    PATH="$CLAWSWEEPER_MODEL_PATH" \
    TMPDIR="$CLAWSWEEPER_MODEL_HOME/tmp" \
    CI=true \
    NO_COLOR=1 \
    COPILOT_GITHUB_TOKEN="$COPILOT_GITHUB_TOKEN" \
    CLAWSWEEPER_ADAPTER_ARTIFACT_DIR="$CLAWSWEEPER_ADAPTER_ARTIFACT_DIR" \
    CLAWSWEEPER_ADAPTER_SCHEMA_DIR="$CLAWSWEEPER_ADAPTER_SCHEMA_DIR" \
    CLAWSWEEPER_ADAPTER_TARGET_DIR="$CLAWSWEEPER_ADAPTER_TARGET_DIR" \
    CLAWSWEEPER_COPILOT_DECISION_MCP="$CLAWSWEEPER_COPILOT_DECISION_MCP" \
    CLAWSWEEPER_COPILOT_EFFORT="$CLAWSWEEPER_COPILOT_EFFORT" \
    CLAWSWEEPER_COPILOT_HOME="$CLAWSWEEPER_COPILOT_HOME" \
    CLAWSWEEPER_COPILOT_MODEL="$CLAWSWEEPER_COPILOT_MODEL" \
    CLAWSWEEPER_PROOF_SCRATCH_DIR="$CLAWSWEEPER_PROOF_SCRATCH_DIR" \
    CLAWSWEEPER_REAL_COPILOT="$CLAWSWEEPER_REAL_COPILOT" \
    GIT_ATTR_NOSYSTEM=1 \
    GIT_CONFIG_GLOBAL="$CLAWSWEEPER_MODEL_GIT_CONFIG" \
    GIT_CONFIG_NOSYSTEM=1 \
    GIT_OPTIONAL_LOCKS=0 \
    GIT_TERMINAL_PROMPT=0 \
    "$CLAWSWEEPER_REAL_CODEX" "$@"
